name: CI-CD

on:
  push:
    branches:
    - main
  
  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Install Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 14.x
        
        - run: npm install
        - run: npm run test:cov
          env:
            CI: true